[profile.default]
src = 'contracts'
solc-version = '0.8.23'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
