apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "l1-volume-indexer.fullname" . }}
  labels:
    {{- include "l1-volume-indexer.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "l1-volume-indexer.selectorLabels" . | nindent 8 }}
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      activeDeadlineSeconds: {{ .Values.cronjob.activeDeadlineSeconds }}
      template:
        metadata:
          labels:
            {{- include "l1-volume-indexer.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args: ["-fill-db"]
              env:
                - name: COVALENT_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "l1-volume-indexer.fullname" . }}-secrets
                      key: covalent-key
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "l1-volume-indexer.fullname" . }}-secrets
                      key: db-host
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "l1-volume-indexer.fullname" . }}-secrets
                      key: db-user
                - name: DB_PW
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "l1-volume-indexer.fullname" . }}-secrets
                      key: db-password
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "l1-volume-indexer.fullname" . }}-secrets
                      key: db-port
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "l1-volume-indexer.fullname" . }}-secrets
                      key: db-name
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
