{{- if .Values.global.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "l1-volume-indexer.fullname" . }}-secrets
  labels:
    {{- include "l1-volume-indexer.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-2"
spec:
  refreshInterval: {{ .Values.global.externalSecrets.refreshInterval | default "12h" }}
  secretStoreRef:
    name: {{ .Values.global.externalSecrets.secretStore }}
    kind: {{ .Values.global.externalSecrets.secretStoreKind | default "ClusterSecretStore" }}
  target:
    name: {{ include "l1-volume-indexer.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-host
      remoteRef:
        key: {{ .Values.envVars.secretName }}
        property: {{ .Values.envVars.database.host }}
    - secretKey: db-user
      remoteRef:
        key: {{ .Values.envVars.secretName }}
        property: {{ .Values.envVars.database.user }}
    - secretKey: db-password
      remoteRef:
        key: {{ .Values.envVars.secretName }}
        property: {{ .Values.envVars.database.password }}
    - secretKey: db-port
      remoteRef:
        key: {{ .Values.envVars.secretName }}
        property: {{ .Values.envVars.database.port }}
    - secretKey: db-name
      remoteRef:
        key: {{ .Values.envVars.secretName }}
        property: {{ .Values.envVars.database.name }}
    - secretKey: covalent-key
      remoteRef:
        key: {{ .Values.envVars.secretName }}
        property: {{ .Values.envVars.covalentKey }}
{{- end }}
